version: '3.8'
services:
   db:
     image: mysql
     entrypoint: docker-entrypoint.sh 
     command: --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
     restart: always
     container_name: mysqldb
     environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysqlpasswd
     networks:
       - mynet
     ports:
       - target: 3306
         published: 3307
     volumes:
       - type: volume
         source: db-data
         target: /var/lib/mysql
     secrets:
       - mysqlpasswd
secrets:                        # top level secrets block
   mysqlpasswd:
     file: passwd.txt
volumes:
   db-data:
networks:
  mynet:
